theme: jekyll-theme-dinky
logo: https://avatars0.githubusercontent.com/u/46445292
title: oracle2mongo
description: Quick Oracle 2 Mongo copy
show_downloads: "true"
include:
  - "_*_.html"
  - "_*_.*.html"